- id: doi:10.3389/fmmed.2022.887733
  title: Nicotinamide Riboside Improves Cardiac Function and Prolongs Survival After Disruption of the Cardiomyocyte Clock
  author:
  - given: Pieterjan
    family: Dierickx
  - given: Bryce J.
    family: Carpenter
  - given: Isaac
    family: Celwyn
  - given: Daniel P.
    family: Kelly
  - given: Joseph A.
    family: Baur
  - given: Mitchell A.
    family: Lazar
  container-title: Frontiers in Molecular Medicine
  date: 2022-5-9
  URL: https://doi.org/gqt4c9
  image: https://www.frontiersin.org/files/Articles/887733/fmmed-02-887733-HTML/image_m/fmmed-02-887733-g001.jpg
  tags: 
      - REV-ERB
      - Cardiomyocyte Clock
      - NAD+
      - circadian clock
