- id: doi:10.3389/fmmed.2022.887733
  title: Nicotinamide Riboside Improves Cardiac Function and Prolongs Survival After Disruption of the Cardiomyocyte Clock
  author:
  - given: Pieterjan
    family: Dierickx
  - given: Bryce J.
    family: Carpenter
  - given: Isaac
    family: Celwyn
  - given: Daniel P.
    family: Kelly
  - given: Joseph A.
    family: Baur
  - given: Mitchell A.
    family: Lazar
  container-title: Frontiers in Molecular Medicine
  date: 2022-5-9
  URL: https://doi.org/gqt4c9
  image: https://www.frontiersin.org/files/Articles/887733/fmmed-02-887733-HTML/image_m/fmmed-02-887733-g001.jpg
  tags: 
      - REV-ERB
      - Cardiomyocyte Clock
      - NAD+
      - circadian clock
  
  
- id: doi:10.1038/s44161-021-00001-9
  container-title: Nature cardiovascular research
  container-title-short: Nat Cardiovasc Res
  ISSN: 2731-0590
  date: 2021-12-23
  author:
  - given: Pieterjan
    family: Dierickx
  - given: Kun
    family: Zhu
  - given: Bryce J
    family: Carpenter
  - given: Chunjie
    family: Jiang
  - given: Marit W
    family: Vermunt
  - given: Yang
    family: Xiao
  - given: Timothy S
    family: Luongo
  - given: Tsunehisa
    family: Yamamoto
  - given: Íngrid
    family: Martí-Pàmies
  - given: Sobuj
    family: Mia
  - given: Mary
    family: Latimer
  - given: Abhinav
    family: Diwan
  - given: Juanjuan
    family: Zhao
  - given: Amy K
    family: Hauck
  - given: Brianna
    family: Krusen
  - given: Hoang C B
    family: Nguyen
  - given: Gerd A
    family: Blobel
  - given: Daniel P
    family: Kelly
  - given: Liming
    family: Pei
  - given: Joseph A
    family: Baur
  - given: Martin E
    family: Young
  - given: Mitchell A
    family: Lazar
  PMID: '35036997'
  PMCID: PMC8754391
  DOI: 10.1038/s44161-021-00001-9
  URL: https://www.ncbi.nlm.nih.gov/pubmed/35036997
  type: article-journal
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8754391/bin/nihms-1749811-f0008.jpg
  tags: 
      - REV-ERB
      - E4bp4
      - NAD+
      - circadian clock
  

- id: doi:10.1016/j.cmet.2020.11.011
  title: The Nuclear Receptor ESRRA Protects from Kidney Disease by Coupling Metabolism and Differentiation
  container-title: Cell metabolism
  container-title-short: Cell Metab
  ISSN: 1932-7420
  date: 2020-12-9
  author:
  - given: Poonam
    family: Dhillon
  - given: Jihwan
    family: Park
  - given: Carmen
    family: Hurtado Del Pozo
  - given: Lingzhi
    family: Li
  - given: Tomohito
    family: Doke
  - given: Shizheng
    family: Huang
  - given: Juanjuan
    family: Zhao
  - given: Hyun Mi
    family: Kang
  - given: Rojesh
    family: Shrestra
  - given: Michael S
    family: Balzer
  - given: Shatakshee
    family: Chatterjee
  - given: Patricia
    family: Prado
  - given: Seung Yub
    family: Han
  - given: Hongbo
    family: Liu
  - given: Xin
    family: Sheng
  - given: Pieterjan
    family: Dierickx
  - given: Kirill
    family: Batmanov
  - given: Juan P
    family: Romero
  - given: Felipe
    family: Prósper
  - given: Mingyao
    family: Li
  - given: Liming
    family: Pei
  - given: Junhyong
    family: Kim
  - given: Nuria
    family: Montserrat
  - given: Katalin
    family: Susztak
  PMID: '33301705'
  PMCID: PMC9259369
  DOI: 10.1016/j.cmet.2020.11.011
  URL: https://www.ncbi.nlm.nih.gov/pubmed/33301705
  type: article-journal
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1550413120306069-fx1_lrg.jpg
  tags: 
      - PT cell differentiation
      - ESRRA protects
      - Kidney Disease
      - scRNA-seq analysis
  
  
- id: doi:10.1016/j.coph.2020.11.006
  container-title: Current opinion in pharmacology
  date: 2020-12-15
  author:
  - given: Nino
    family: Chirico
  - given: Linda W
    family: Van Laake
  - given: Joost P G
    family: Sluijter
  - given: Alain
    family: van Mil
  - given: Pieterjan
    family: Dierickx
  PMID: '33338891'
  DOI: 10.1016/j.coph.2020.11.006
  URL: https://www.ncbi.nlm.nih.gov/pubmed/33338891
  type: article-journal
  tags: 
      - Circadian rhythms
      - Regeneration 
      - Stem cells
      - Tissue engineering
      - Clock manipulation
      - Extracellular matrix
  
- id: doi:10.1126/science.aba8984
  title: The hepatocyte clock and feeding control chronophysiology of multiple liver cell types
  container-title: Science
  container-title-short: Science
  ISSN: 1095-9203
  date: 2020-7-30
  author:
  - given: Dongyin
    family: Guan
  - given: Ying
    family: Xiong
  - given: Trang Minh
    family: Trinh
  - given: Yang
    family: Xiao
  - given: Wenxiang
    family: Hu
  - given: Chunjie
    family: Jiang
  - given: Pieterjan
    family: Dierickx
  - given: Cholsoon
    family: Jang
  - given: Joshua D
    family: Rabinowitz
  - given: Mitchell A
    family: Lazar
  PMID: '32732282'
  PMCID: PMC7849028
  DOI: 10.1126/science.aba8984
  URL: https://www.ncbi.nlm.nih.gov/pubmed/32732282
  type: article-journal
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7849028/bin/nihms-1662085-f0001.jpg

  
  
- id: doi:10.1073/pnas.1904226116
  container-title: Proceedings of the National Academy of Sciences of the United States of America
  container-title-short: Proc Natl Acad Sci U S A
  ISSN: 1091-6490
  date: 2019-5-24
  author:
  - given: Pieterjan
    family: Dierickx
  - given: Matthew J
    family: Emmett
  - given: Chunjie
    family: Jiang
  - given: Kahealani
    family: Uehara
  - given: Manlu
    family: Liu
  - given: Marine
    family: Adlanmerini
  - given: Mitchell A
    family: Lazar
  PMID: '31127047'
  PMCID: PMC6589768
  DOI: 10.1073/pnas.1904226116
  URL: https://www.ncbi.nlm.nih.gov/pubmed/31127047
  type: article-journal
  image: https://www.pnas.org/cms/10.1073/pnas.1904226116/asset/3ccb1516-a62e-4ed0-9f2d-c250da067067/assets/graphic/pnas.1904226116fig01.jpeg
  tags: 
      - REV-ERB
 
- id: doi:10.1016/j.stem.2018.11.018
  title: Patient Adipose Stem Cell-Derived Adipocytes Reveal Genetic Variation that Predicts Antidiabetic Drug Response
  container-title: Cell stem cell
  container-title-short: Cell Stem Cell
  ISSN: 1875-9777
  date: 2019-1-10
  author:
  - given: Wenxiang
    family: Hu
  - given: Chunjie
    family: Jiang
  - given: Dongyin
    family: Guan
  - given: Pieterjan
    family: Dierickx
  - given: Rong
    family: Zhang
  - given: Arden
    family: Moscati
  - given: Girish N
    family: Nadkarni
  - given: David J
    family: Steger
  - given: Ruth J F
    family: Loos
  - given: Cheng
    family: Hu
  - given: Weiping
    family: Jia
  - given: Raymond E
    family: Soccio
  - given: Mitchell A
    family: Lazar
  PMID: '30639037'
  PMCID: PMC6368460
  DOI: 10.1016/j.stem.2018.11.018
  URL: https://www.ncbi.nlm.nih.gov/pubmed/30639037
  type: article-journal
  image: https://ars.els-cdn.com/content/image/1-s2.0-S193459091830554X-fx1.jpg
 
 
- id: doi:10.15252/embr.201745130
  container-title: EMBO reports
  container-title-short: EMBO Rep
  ISSN: 1469-3178
  date: 2017-12-19
  author:
  - given: Pieterjan
    family: Dierickx
  - given: Linda W
    family: Van Laake
  - given: Niels
    family: Geijsen
  PMID: '29258993'
  PMCID: PMC5757216
  DOI: 10.15252/embr.201745130
  URL: https://www.ncbi.nlm.nih.gov/pubmed/29258993
  type: article-journal
  image: https://www.embopress.org/cms/asset/9346f393-0bc7-421b-9664-ed7a3776bf4a/embr201745130-fig-0001-m.jpg

     
- id: doi:10.1016/j.yjmcc.2017.08.009
  title: Neonatal rat cardiomyocytes as an in vitro model for circadian rhythms in the heart
  container-title: Journal of molecular and cellular cardiology
  container-title-short: J Mol Cell Cardiol
  ISSN: 1095-8584
  date: 2017-8-18
  author:
  - given: Bastiaan C
    family: du Pré
  - given: Pieterjan
    family: Dierickx
  - given: Sandra
    family: Crnko
  - given: Pieter A
    family: Doevendans
  - given: Marc A
    family: Vos
  - given: Niels
    family: Geijsen
  - given: Didi
    family: Neutel
  - given: Toon A B
    family: van Veen
  - given: Linda W
    family: van Laake
  PMID: '28823816'
  DOI: 10.1016/j.yjmcc.2017.08.009
  URL: https://www.ncbi.nlm.nih.gov/pubmed/28823816
  type: article-journal
  image: https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/24dd67af-e4e1-4fde-90dc-6f37149f2659/gr1.jpg
  tags: 
      - Circadian rhythms
      - Heart
      - In vitro
      - Neonatal rat cardiomyocytes


- id: doi:10.1016/j.stemcr.2017.07.010
  container-title: Stem cell reports
  container-title-short: Stem Cell Reports
  ISSN: 2213-6711
  date: 2017-8-10
  author:
  - given: Bastiaan C
    family: Du Pré
  - given: Evelyne J
    family: Demkes
  - given: Dries A M
    family: Feyen
  - given: Pieterjan
    family: Dierickx
  - given: Sandra
    family: Crnko
  - given: Bart J M
    family: Kok
  - given: Joost P G
    family: Sluijter
  - given: Pieter A
    family: Doevendans
  - given: Marc A
    family: Vos
  - given: Toon A B
    family: Van Veen
  - given: Linda W
    family: Van Laake
  PMID: '28803917'
  PMCID: PMC5599230
  DOI: 10.1016/j.stemcr.2017.07.010
  URL: https://www.ncbi.nlm.nih.gov/pubmed/28803917
  type: article-journal
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5599230/bin/gr1.jpg
  tags: 
      - SCA1
      - circadian rhythm
      - clock 
      - heart 
      - progenitor cell
      - stem cell

- id: doi:10.1021/acssensors.7b00239
  title: Bright Bioluminescent BRET Sensor Proteins for Measuring Intracellular Caspase Activity
  container-title: ACS sensors
  container-title-short: ACS Sens
  ISSN: 2379-3694
  date: 2017-5-31
  author:
  - given: Anniek
    family: den Hamer
  - given: Pieterjan
    family: Dierickx
  - given: Remco
    family: Arts
  - given: Joost S P M
    family: de Vries
  - given: Luc
    family: Brunsveld
  - given: Maarten
    family: Merkx
  PMID: '28670623'
  PMCID: PMC5485374
  DOI: 10.1021/acssensors.7b00239
  URL: https://www.ncbi.nlm.nih.gov/pubmed/28670623
  type: article-journal
  image: https://pubs.acs.org/cms/10.1021/acssensors.7b00239/asset/images/medium/se-2017-002393_0001.gif
  tags: 
       - caspase sensor
       - BRET 
       - NanoLuc 
       - mNeonGreen 
       - plate reader assay 
       - single-cell imaging
       

 
- id: doi:10.15252/embr.201743897
  title: Circadian networks in human embryonic stem cell-derived cardiomyocytes
  container-title: EMBO reports
  container-title-short: EMBO Rep
  ISSN: 1469-3178
  date: 2017-5-23
  author:
  - given: Pieterjan
    family: Dierickx
  - given: Marit W
    family: Vermunt
  - given: Mauro J
    family: Muraro
  - given: Menno P
    family: Creyghton
  - given: Pieter A
    family: Doevendans
  - given: Alexander
    family: van Oudenaarden
  - given: Niels
    family: Geijsen
  - given: Linda W
    family: Van Laake
  PMID: '28536247'
  PMCID: PMC5494509
  DOI: 10.15252/embr.201743897
  URL: https://www.ncbi.nlm.nih.gov/pubmed/28536247
  type: article-journal
  image: https://www.embopress.org/cms/asset/6ea9641a-6ceb-484d-8a21-894542eff600/embr201743897-fig-0001-m.jpg
  tags: 
      - circadian clock
      - heart
  
  
- id: doi:10.1161/circulationaha.116.024145
  title: Defined Engineered Human Myocardium With Advanced Maturation for Applications in Heart Failure Modeling and Repair
  container-title: Circulation
  container-title-short: Circulation
  ISSN: 1524-4539
  date: 2017-2-6
  author:
  - given: Malte
    family: Tiburcy
  - given: James E
    family: Hudson
  - given: Paul
    family: Balfanz
  - given: Susanne
    family: Schlick
  - given: Tim
    family: Meyer
  - given: Mei-Ling
    family: Chang Liao
  - given: Elif
    family: Levent
  - given: Farah
    family: Raad
  - given: Sebastian
    family: Zeidler
  - given: Edgar
    family: Wingender
  - given: Johannes
    family: Riegler
  - given: Mouer
    family: Wang
  - given: Joseph D
    family: Gold
  - given: Izhak
    family: Kehat
  - given: Erich
    family: Wettwer
  - given: Ursula
    family: Ravens
  - given: Pieterjan
    family: Dierickx
  - given: Linda W
    family: van Laake
  - given: Marie Jose
    family: Goumans
  - given: Sara
    family: Khadjeh
  - given: Karl
    family: Toischer
  - given: Gerd
    family: Hasenfuss
  - given: Larry A
    family: Couture
  - given: Andreas
    family: Unger
  - given: Wolfgang A
    family: Linke
  - given: Toshiyuki
    family: Araki
  - given: Benjamin
    family: Neel
  - given: Gordon
    family: Keller
  - given: Lior
    family: Gepstein
  - given: Joseph C
    family: Wu
  - given: Wolfram-Hubertus
    family: Zimmermann
  PMID: '28167635'
  PMCID: PMC5501412
  DOI: 10.1161/circulationaha.116.024145
  URL: https://www.ncbi.nlm.nih.gov/pubmed/28167635
  type: article-journal
  image: https://www.ahajournals.org/cms/asset/ed1397d0-e529-4729-82fa-6f2c0f116f94/1832fig01.jpg
  tags: 
      - Heart Failure
      - Engineered Human Myocardium
 
      
      
- id:  doi:10.1021/acschembio.6b00453
  container-title: ACS chemical biology
  container-title-short: ACS Chem Biol
  ISSN: 1554-8937
  date: 2016-9-1
  author:
  - given: Stijn J A
    family: Aper
  - given: Pieterjan
    family: Dierickx
  - given: Maarten
    family: Merkx
  PMID: '27547982'
  PMCID: PMC5080634
  DOI: 10.1021/acschembio.6b00453
  URL: https://www.ncbi.nlm.nih.gov/pubmed/27547982
  type: article-journal
  image: https://pubs.acs.org/cms/10.1021/acschembio.6b00453/asset/images/medium/cb-2016-004539_0007.gif
  tags: 
     - BRET/FRET

  
- id: doi:10.1083/jcb.201601074
  container-title: The Journal of cell biology
  container-title-short: J Cell Biol
  ISSN: 1540-8140
  date: 2016-2-8
  author:
  - given: Pieterjan
    family: Dierickx
  - given: Linda W
    family: Van Laake
  PMID: '26858264'
  PMCID: PMC4754721
  DOI: 10.1083/jcb.201601074
  URL: https://www.ncbi.nlm.nih.gov/pubmed/26858264
  type: article-journal
  image: https://rupress.org/view-large/figure/6925064/JCB_201601074_Fig1.jpeg
  tags: 
       - Adhesion
       - Biophysics 
       - Cell signaling
       - Cytoskeleton
       - Membrane and lipid biology
       - Physiology
       - Stem cells
       - Systems and Computational Biology
       
       
  
- id: doi:10.1007/s12015-013-9458-z
  container-title: Stem cell reviews and reports
  container-title-short: Stem Cell Rev Rep
  ISSN: 2629-3277
  date: 2013-12
  author:
  - given: Lieven
    family: Haenebalcke
  - given: Steven
    family: Goossens
  - given: Michael
    family: Naessens
  - given: Natascha
    family: Kruse
  - given: Morvarid
    family: Farhang Ghahremani
  - given: Sonia
    family: Bartunkova
  - given: Katharina
    family: Haigh
  - given: Tim
    family: Pieters
  - given: Pieterjan
    family: Dierickx
  - given: Benjamin
    family: Drogat
  - given: Omar
    family: Nyabi
  - given: Dagmar
    family: Wirth
  - given: Jody J
    family: Haigh
  PMID: '23877658'
  DOI: 10.1007/s12015-013-9458-z
  URL: https://www.ncbi.nlm.nih.gov/pubmed/23877658
  type: article-journal
  

  
- id: doi:10.1016/j.celrep.2013.01.016
  container-title: Cell reports
  container-title-short: Cell Rep
  ISSN: 2211-1247
  date: 2013-2-7
  author:
  - given: Lieven
    family: Haenebalcke
  - given: Steven
    family: Goossens
  - given: Pieterjan
    family: Dierickx
  - given: Sonia
    family: Bartunkova
  - given: Jinke
    family: D'Hont
  - given: Katharina
    family: Haigh
  - given: Tino
    family: Hochepied
  - given: Dagmar
    family: Wirth
  - given: Andras
    family: Nagy
  - given: Jody J
    family: Haigh
  PMID: '23395636'
  DOI: 10.1016/j.celrep.2013.01.016
  URL: https://www.ncbi.nlm.nih.gov/pubmed/23395636
  type: article-journal
  image: https://www.cell.com/cms/attachment/361a00ac-07ac-4d01-98db-91755e9b131f/fx1.jpg

      
      
- id: doi:10.1007/s12265-012-9391-6
  container-title: Journal of cardiovascular translational research
  container-title-short: J Cardiovasc Transl Res
  ISSN: 1937-5395
  date: 2012-7-18
  author:
  - given: Pieterjan
    family: Dierickx
  - given: Pieter A
    family: Doevendans
  - given: Niels
    family: Geijsen
  - given: Linda W
    family: van Laake
  PMID: '22806916'
  DOI: 10.1007/s12265-012-9391-6
  URL: https://www.ncbi.nlm.nih.gov/pubmed/22806916
  type: article-journal
  
 - id: doi:10.1007/978-3-319-25427-2_5
  authors:
  - Pieterjan Dierickx
  - Pieter A. Doevendans
  - Niels Geijsen
  - Linda W. van Laake
  publisher: Stem Cell Biology and Regenerative Medicine
  date: '2015-12-18'
  - given: Pieterjan
    family: Dierickx
  - given: Pieter A
    family: Doevendans
  - given: Niels
    family: Geijsen
  - given: Linda W
    family: van Laake
  - given: Bastiaan D
    family: Pré
  - given: Toon
    family: van Veen
  - given: Dries A. M.
    family: Feyen  
  DOI: 10.1007/978-3-319-25427-2_5
  URL: https://link.springer.com/chapter/10.1007/978-3-319-25427-2_5
  type: article-journal
   


